simulation:
  map_yaml_file: "config/maps/square_2x2.yaml"
  agent_yaml_file: "config/agents/simple/two_cars_ped.yaml"
  ontology_yaml_file: "config/rules/ontology_simple.yaml"
  rule_type: "Z3_Expert"
  rule_yaml_file: "config/rules/Nav/easy/expert_simple.yaml"
  rl: true
  debug: false
  use_multi: false
  agent_region: 100
  rl_agent:
    max_priority: 2
    use_expert: true
    agent_names: ["Car_1", "Car_2"]
    require_ped_route_intersection: true
    require_car_route_intersection: true
    sample_attempts: 50
    max_horizon: 200
    action_space: 2
    action_mapping:
      0: [0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0]
      1: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
    fov_entities:
      Entity: 2
    action_cost:
      0: 0
      1: -2
    overtime_cost: -6

stable_baselines:
  algorithm: "PPO"
  policy_network: "MlpPolicy"
  policy_kwargs:
    features_extractor_module: "logicity.rl_agent.policy.neural"
    features_extractor_class: "MLPFeatureExtractor"
    features_extractor_kwargs:
      features_dim: 32
  hyperparameters:
    learning_rate: 0.0003
    clip_range: 0.2
    vf_coef: 0.5
    batch_size: 64
    n_steps: 256
    n_epochs: 10
    ent_coef: 0.001
    verbose: 1
    tensorboard_log: "./tb_logs"
  train: false
  checkpoint_path: "checkpoints/best_model.zip"
