simulation:
  map_yaml_file: "config/maps/square_2x2.yaml"
  agent_yaml_file: "config/agents/simple/two_cars_ped.yaml"
  ontology_yaml_file: "config/rules/ontology_simple.yaml"
  rule_type: "Z3_Expert"
  rule_yaml_file: "config/rules/Nav/easy/expert_simple.yaml"
  rl: true
  debug: false
  use_multi: false
  agent_region: 100
  rl_agent:
    max_priority: 3
    use_expert: true
    agent_name: "Car_1"
    randomize_all_car_priorities: true
    require_all_pairwise_interactions: true
    require_center_intersection_crossing: true
    max_arrival_gap: 5
    max_horizon: 200
    action_space: 2
    action_mapping:
      0: [0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0]
      1: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
    fov_entities:
      Entity: 3
    action_cost:
      0: 0
      1: -2

stable_baselines:
  algorithm: "ExpertCollector"
  train: false
  policy_kwargs:
    num_episodes: -1
    return_full_world: false
  hyperparameters:
    None
